language: python
python:
  - "3.4"
cache: pip
addons:
  hosts:
    - rediska
    - mongodb
services:
  - mongodb
  - redis-server
install:
  - pip install -r requirements.txt
script:
  - python -m unittest -v test_server_paste
